permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: "page/:num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js]



title: "bit-ranger"
email: mreden@163.com
description: ""
github:
  username: bit-ranger
swiftype:
  searchId: iXZyPokVfxFaBTvi64Y6
gitment:
    repo: https://goroutine.me
    client_id: cf3b009d23ac36f71836
    client_secret: a242e31bea418f9d3fa90d7606a7443750825ba8

url: "https://goroutine.me"
imgrepo: "https://goroutine.me/static/img"


#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

