# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Goroutine
name: Goroutine
email: mreden@163.com
location: Suzhou, China
company: Personnel
company_url: https://www.goroutine.me
github_url: https://github.com/selfjt
description: This is personnel website of Goroutine
favicon: favicon.png # Image must be in assets/images

url: https://www.goroutine.me # the base hostname & protocol for your site

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: mreden.disqus.com

#gitment
comment_gitment_owner: mreden@163.com
comment_gitment_repo: https://www.goroutine.me
comment_gitment_clientId: cf3b009d23ac36f71836
comment_gitment_clientSecret: a242e31bea418f9d3fa90d7606a7443750825ba8

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-source

  -
    href: /blog
    label: Blog

  -
    href: /bookmark
    label: Bookmark

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'UA-86221408-3'
      optimize_id : 'GTM-TR7MHHT'
      google_ad_client: 'ca-pub-5784279524799575'


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, Go, Python, MySQL, Oracle, SQLite, PHP, Linux, Nginx, Algorithm]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, MongoDB, Redis, PHP, Symfony, Boostrap]
skill_mobile_app_keywords: [Android]